### ISSUE TITLE
Missing a module required for Belati

### ISSUE THREAD

**Issue by PentestTeam** [aancw/Belati#13] opened 2017-10-04 13:46 UTC
Hello! 
Thanks for such beautiful project. But I can't run it:
![image](https://user-images.githubusercontent.com/31402032/31179035-76fabb9a-a923-11e7-85ce-541fe5f7b87c.png)

I'm on 
Linux 4.12.0-kali2-amd64 #1 SMP Debian 4.12.12-2kali1 (2017-09-13) x86_64 GNU/Linux

**Comment by ghost** [comment] 2017-10-04 15:13
I have this problem too.

**Comment by aancw** [comment] 2017-10-04 15:21
Hy, so many people have problems in this checker. As mentioned above, this is just because Belati not able to detect that plugins. I need to reproduce this issue in my environment. I'm using Arch Linux and Kali but no problem about deps.

This will be my todo -> https://github.com/aancw/Belati/issues/14

**Comment by aancw** [comment] 2017-10-04 15:29
Fresh install in Kali2 https://github.com/aancw/Belati/issues/4#issuecomment-307548924

**Comment by aancw** [comment] 2017-10-04 15:43
Refer to closed issue https://github.com/aancw/Belati/issues/2

Can you uninstall and install that package again? Let me know if this is working

**Comment by 0xbadshah** [comment] 2017-10-04 16:16
Hey @PentestTeam Please comment the output of `pip freeze`.

**Comment by PentestTeam** [comment] 2017-10-04 16:25
I runs for every module:
`pip install --upgrade --force-reinstall [modulename]`
and solved my problem! Thx everyone!

![image](https://user-images.githubusercontent.com/31402032/31187111-7c7e520a-a939-11e7-94c2-f05f7d1ec652.png)

![image](https://user-images.githubusercontent.com/31402032/31187187-c8ae8974-a939-11e7-9618-8bb97bf30696.png)

**Comment by 0xbadshah** [comment] 2017-10-04 16:29
Thats what I just mentioned in a [comment](https://github.com/aancw/Belati/issues/14#issuecomment-334212572) in #14.

**Comment by 0xbadshah** [comment] 2017-10-04 16:29
I think its time to close the issue. :smile:

**Closed as completed** 2017-10-04 16:30 UTC
